// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    "IconMdi:email": typeof import("~icons/mdi/email")["default"]
    "IconMdi:github": typeof import("~icons/mdi/github")["default"]
    "IconMdi:linkedin": typeof import("~icons/mdi/linkedin")["default"]
  }
}

export { }
